
-----------------------------------------------------------------------------
-- TRANSACTION_MAPPER
-----------------------------------------------------------------------------
DROP TABLE TRANSACTION_MAPPER CASCADE CONSTRAINTS PURGE;

CREATE TABLE TRANSACTION_MAPPER
(
  ID NUMBER (20, 0) NOT NULL,
  BEFORE_TRANSACTION_ID NUMBER (20, 0) NOT NULL,
  AFTER_TRANSACTION_ID NUMBER (20, 0),
    CONSTRAINT unq_TRANSACTION_MAPPER_1 UNIQUE (BEFORE_TRANSACTION_ID, AFTER_TRANSACTION_ID)
);
ALTER TABLE TRANSACTION_MAPPER
    ADD CONSTRAINT TRANSACTION_MAPPER_PK
PRIMARY KEY (ID);



COMMENT ON TABLE TRANSACTION_MAPPER IS 'トランザクション変遷マッパー';
COMMENT ON COLUMN TRANSACTION_MAPPER.ID IS 'OID';
COMMENT ON COLUMN TRANSACTION_MAPPER.BEFORE_TRANSACTION_ID IS '元予定トランザクションId';
COMMENT ON COLUMN TRANSACTION_MAPPER.AFTER_TRANSACTION_ID IS '先トランザクションId';


-----------------------------------------------------------------------------
-- ENTRY
-----------------------------------------------------------------------------
DROP TABLE ENTRY CASCADE CONSTRAINTS PURGE;

CREATE TABLE ENTRY
(
  ID NUMBER (20, 0) NOT NULL,
  QUANTITY NUMBER (20, 0) NOT NULL,
  ACCOUNT_ID NUMBER (20, 0) NOT NULL,
  TRANSACTION_ID NUMBER (20, 0) NOT NULL
);
ALTER TABLE ENTRY
    ADD CONSTRAINT ENTRY_PK
PRIMARY KEY (ID);



COMMENT ON TABLE ENTRY IS 'エントリー';
COMMENT ON COLUMN ENTRY.ID IS 'OID';
COMMENT ON COLUMN ENTRY.QUANTITY IS '移動量';
COMMENT ON COLUMN ENTRY.ACCOUNT_ID IS '勘定ID';
COMMENT ON COLUMN ENTRY.TRANSACTION_ID IS 'トランザクションID';


-----------------------------------------------------------------------------
-- TRANSACTION
-----------------------------------------------------------------------------
DROP TABLE TRANSACTION CASCADE CONSTRAINTS PURGE;

CREATE TABLE TRANSACTION
(
  ID NUMBER (20, 0) NOT NULL,
  ACTUAL CHAR NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL,
  PROCESS_DATE TIMESTAMP NOT NULL
);
ALTER TABLE TRANSACTION
    ADD CONSTRAINT TRANSACTION_PK
PRIMARY KEY (ID);



COMMENT ON TABLE TRANSACTION IS 'トランザクション';
COMMENT ON COLUMN TRANSACTION.ID IS 'OID';
COMMENT ON COLUMN TRANSACTION.ACTUAL IS '実績の取引の場合はY。予定はN';
COMMENT ON COLUMN TRANSACTION.REGISTER_DATE IS '入力日';
COMMENT ON COLUMN TRANSACTION.PROCESS_DATE IS '取引日';


-----------------------------------------------------------------------------
-- ACCOUNT
-----------------------------------------------------------------------------
DROP TABLE ACCOUNT CASCADE CONSTRAINTS PURGE;

CREATE TABLE ACCOUNT
(
  ID NUMBER (20, 0) NOT NULL,
  PLACE_ID NUMBER (20, 0) NOT NULL,
  ITEM_ID NUMBER (20, 0) NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL,
  OWNER_ID NUMBER (20, 0) NOT NULL,
    CONSTRAINT unq_ACCOUNT_1 UNIQUE (PLACE_ID, ITEM_ID, OWNER_ID)
);
ALTER TABLE ACCOUNT
    ADD CONSTRAINT ACCOUNT_PK
PRIMARY KEY (ID);



COMMENT ON TABLE ACCOUNT IS '勘定';
COMMENT ON COLUMN ACCOUNT.ID IS 'OID';
COMMENT ON COLUMN ACCOUNT.PLACE_ID IS '場所ID';
COMMENT ON COLUMN ACCOUNT.ITEM_ID IS '品目ID';
COMMENT ON COLUMN ACCOUNT.REGISTER_DATE IS '勘定作成日';
COMMENT ON COLUMN ACCOUNT.OWNER_ID IS '所有者ID';


-----------------------------------------------------------------------------
-- PLACE
-----------------------------------------------------------------------------
DROP TABLE PLACE CASCADE CONSTRAINTS PURGE;

CREATE TABLE PLACE
(
  ID NUMBER (20, 0) NOT NULL,
  NAME VARCHAR2 (256) NOT NULL,
  VIRTUAL CHAR default 'N' NOT NULL,
  PARENT_ID NUMBER (20, 0),
  OWNER_ID NUMBER (20, 0) NOT NULL
);
ALTER TABLE PLACE
    ADD CONSTRAINT PLACE_PK
PRIMARY KEY (ID);



COMMENT ON TABLE PLACE IS '場所';
COMMENT ON COLUMN PLACE.ID IS 'OID';
COMMENT ON COLUMN PLACE.NAME IS '場所名';
COMMENT ON COLUMN PLACE.VIRTUAL IS '論理的な場所';
COMMENT ON COLUMN PLACE.PARENT_ID IS '親場所ID';
COMMENT ON COLUMN PLACE.OWNER_ID IS '所有者OID';


-----------------------------------------------------------------------------
-- ITEM
-----------------------------------------------------------------------------
DROP TABLE ITEM CASCADE CONSTRAINTS PURGE;

CREATE TABLE ITEM
(
  ID NUMBER (20, 0) NOT NULL,
  NAME VARCHAR2 (256) NOT NULL,
  PARENT_ID NUMBER (20, 0)
);
ALTER TABLE ITEM
    ADD CONSTRAINT ITEM_PK
PRIMARY KEY (ID);



COMMENT ON TABLE ITEM IS '品目';
COMMENT ON COLUMN ITEM.ID IS 'OID';
COMMENT ON COLUMN ITEM.NAME IS '品目名';
COMMENT ON COLUMN ITEM.PARENT_ID IS '親品目ID';


-----------------------------------------------------------------------------
-- OWNER
-----------------------------------------------------------------------------
DROP TABLE OWNER CASCADE CONSTRAINTS PURGE;

CREATE TABLE OWNER
(
  ID NUMBER (20, 0) NOT NULL,
  NAME VARCHAR2 (256) NOT NULL
);
ALTER TABLE OWNER
    ADD CONSTRAINT OWNER_PK
PRIMARY KEY (ID);



COMMENT ON TABLE OWNER IS '所有者';
COMMENT ON COLUMN OWNER.ID IS 'OID';
COMMENT ON COLUMN OWNER.NAME IS '所有者名';

